# Generated by Django 2.0.4 on 2018-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2018914659423447144c7d7e72', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_201891465942347533eb3f25ae', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
